    
        --guydir = (guydir + 15 * dt) % 360

        -- draw guy
    -- x, y = love.mouse.getPosition()
    -- for startAngle = guydir, guydir + 359, 30 do
    --     pingraph.setColor(.3, 1, .3)
    --     pingraph.setLineWidth(1)
    --     angleToMouse = getDir(guyx, guyy, x, y)
    --     print(angleToMouse)
    --     endAngle = startAngle + 30
    --     if endAngle > 360 then
    --         startAngle = startAngle - 360
    --         endAngle = endAngle - 360
    --     end
    --     pingraph.print(angleToMouse, 100, 100)
    --     pingraph.print(startAngle, 100, 200 + startAngle / 2)
    --     pingraph.print(endAngle, 100, 400 + startAngle / 2)

    --     if (getDistance(guyx, guyy, x, y) > 100 and getDistance(guyx, guyy, x, y) < 200) and angleToMouse > startAngle and angleToMouse < endAngle then
    --         pingraph.setColor(.3, .3, 1)
    --         pingraph.arc('fill',guyx,guyy, 200, math.rad(startAngle), math.rad(startAngle+30))
    --     end
    --     pingraph.setColor(.3, 1, .3)
    --     pingraph.arc('line',guyx,guyy, 200, math.rad(startAngle), math.rad(startAngle+30))
    --     pingraph.setLineWidth(3)
    --     pingraph.circle('line', guyx, guyy, 200)
    --     pingraph.setColor(.1,.5,.1)
    --     pingraph.circle('fill', guyx, guyy, 100)
    --     pingraph.setColor(.3, 1, .3)
    --     pingraph.circle('line', guyx, guyy, 100)
    -- end